/** THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
 * BY HAND!!
 *
 * Generated by lcm-gen
 **/

#ifndef __Dutta_Barua_JOIN_response_hpp__
#define __Dutta_Barua_JOIN_response_hpp__

#include <lcm/lcm_coretypes.h>

#include <vector>
#include "Dutta_Barua_cert.hpp"
#include "Dutta_Barua_cert.hpp"
#include "Dutta_Barua_cert.hpp"


class Dutta_Barua_JOIN_response
{
    public:
        uint8_t    att_randomlocal[32];

        uint8_t    att_challenge[32];

        int32_t    n_observed_challenges;

        std::vector< std::vector< uint8_t > > att_observed_challenges;

        int64_t    timestamp_r1start_us;

        int32_t    participants;

        std::vector< Dutta_Barua_cert > certificates_participants;

        int32_t    joining;

        std::vector< Dutta_Barua_cert > certificates_joining;

        /**
         * certificate of sender, not included in certificates_joining or certificates_participants
         * used to sign signature
         */
        Dutta_Barua_cert self;

        int32_t    role;

        int32_t    sig_size;

        std::vector< uint8_t > sig;

    public:
        enum { att_randomness_bytes = 32 };
        /// Role of sender
        enum { ROLE_JOINING = 1 };
        enum { ROLE_PARTICIPANT = 2 };

    public:
        /**
         * Encode a message into binary form.
         *
         * @param buf The output buffer.
         * @param offset Encoding starts at thie byte offset into @p buf.
         * @param maxlen Maximum number of bytes to write.  This should generally be
         *  equal to getEncodedSize().
         * @return The number of bytes encoded, or <0 on error.
         */
        inline int encode(void *buf, int offset, int maxlen) const;

        /**
         * Check how many bytes are required to encode this message.
         */
        inline int getEncodedSize() const;

        /**
         * Decode a message from binary form into this instance.
         *
         * @param buf The buffer containing the encoded message.
         * @param offset The byte offset into @p buf where the encoded message starts.
         * @param maxlen The maximum number of bytes to read while decoding.
         * @return The number of bytes decoded, or <0 if an error occured.
         */
        inline int decode(const void *buf, int offset, int maxlen);

        /**
         * Retrieve the 64-bit fingerprint identifying the structure of the message.
         * Note that the fingerprint is the same for all instances of the same
         * message type, and is a fingerprint on the message type definition, not on
         * the message contents.
         */
        inline static int64_t getHash();

        /**
         * Returns "Dutta_Barua_JOIN_response"
         */
        inline static const char* getTypeName();

        // LCM support functions. Users should not call these
        inline int _encodeNoHash(void *buf, int offset, int maxlen) const;
        inline int _getEncodedSizeNoHash() const;
        inline int _decodeNoHash(const void *buf, int offset, int maxlen);
        inline static uint64_t _computeHash(const __lcm_hash_ptr *p);
};

int Dutta_Barua_JOIN_response::encode(void *buf, int offset, int maxlen) const
{
    int pos = 0, tlen;
    int64_t hash = getHash();

    tlen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &hash, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = this->_encodeNoHash(buf, offset + pos, maxlen - pos);
    if (tlen < 0) return tlen; else pos += tlen;

    return pos;
}

int Dutta_Barua_JOIN_response::decode(const void *buf, int offset, int maxlen)
{
    int pos = 0, thislen;

    int64_t msg_hash;
    thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &msg_hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;
    if (msg_hash != getHash()) return -1;

    thislen = this->_decodeNoHash(buf, offset + pos, maxlen - pos);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int Dutta_Barua_JOIN_response::getEncodedSize() const
{
    return 8 + _getEncodedSizeNoHash();
}

int64_t Dutta_Barua_JOIN_response::getHash()
{
    static int64_t hash = static_cast<int64_t>(_computeHash(NULL));
    return hash;
}

const char* Dutta_Barua_JOIN_response::getTypeName()
{
    return "Dutta_Barua_JOIN_response";
}

int Dutta_Barua_JOIN_response::_encodeNoHash(void *buf, int offset, int maxlen) const
{
    int pos = 0, tlen;

    tlen = __byte_encode_array(buf, offset + pos, maxlen - pos, &this->att_randomlocal[0], 32);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __byte_encode_array(buf, offset + pos, maxlen - pos, &this->att_challenge[0], 32);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &this->n_observed_challenges, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    for (int a0 = 0; a0 < this->n_observed_challenges; a0++) {
        tlen = __byte_encode_array(buf, offset + pos, maxlen - pos, &this->att_observed_challenges[a0][0], 32);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    tlen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &this->timestamp_r1start_us, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &this->participants, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    for (int a0 = 0; a0 < this->participants; a0++) {
        tlen = this->certificates_participants[a0]._encodeNoHash(buf, offset + pos, maxlen - pos);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    tlen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &this->joining, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    for (int a0 = 0; a0 < this->joining; a0++) {
        tlen = this->certificates_joining[a0]._encodeNoHash(buf, offset + pos, maxlen - pos);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    tlen = this->self._encodeNoHash(buf, offset + pos, maxlen - pos);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &this->role, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &this->sig_size, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    if(this->sig_size > 0) {
        tlen = __byte_encode_array(buf, offset + pos, maxlen - pos, &this->sig[0], this->sig_size);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    return pos;
}

int Dutta_Barua_JOIN_response::_decodeNoHash(const void *buf, int offset, int maxlen)
{
    int pos = 0, tlen;

    tlen = __byte_decode_array(buf, offset + pos, maxlen - pos, &this->att_randomlocal[0], 32);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __byte_decode_array(buf, offset + pos, maxlen - pos, &this->att_challenge[0], 32);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &this->n_observed_challenges, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    try {
        this->att_observed_challenges.resize(this->n_observed_challenges);
    } catch (...) {
        return -1;
    }
    for (int a0 = 0; a0 < this->n_observed_challenges; a0++) {
        if(32) {
            this->att_observed_challenges[a0].resize(32);
            tlen = __byte_decode_array(buf, offset + pos, maxlen - pos, &this->att_observed_challenges[a0][0], 32);
            if(tlen < 0) return tlen; else pos += tlen;
        }
    }

    tlen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &this->timestamp_r1start_us, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &this->participants, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    try {
        this->certificates_participants.resize(this->participants);
    } catch (...) {
        return -1;
    }
    for (int a0 = 0; a0 < this->participants; a0++) {
        tlen = this->certificates_participants[a0]._decodeNoHash(buf, offset + pos, maxlen - pos);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    tlen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &this->joining, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    try {
        this->certificates_joining.resize(this->joining);
    } catch (...) {
        return -1;
    }
    for (int a0 = 0; a0 < this->joining; a0++) {
        tlen = this->certificates_joining[a0]._decodeNoHash(buf, offset + pos, maxlen - pos);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    tlen = this->self._decodeNoHash(buf, offset + pos, maxlen - pos);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &this->role, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &this->sig_size, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    if(this->sig_size) {
        this->sig.resize(this->sig_size);
        tlen = __byte_decode_array(buf, offset + pos, maxlen - pos, &this->sig[0], this->sig_size);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    return pos;
}

int Dutta_Barua_JOIN_response::_getEncodedSizeNoHash() const
{
    int enc_size = 0;
    enc_size += __byte_encoded_array_size(NULL, 32);
    enc_size += __byte_encoded_array_size(NULL, 32);
    enc_size += __int32_t_encoded_array_size(NULL, 1);
    enc_size += this->n_observed_challenges * __byte_encoded_array_size(NULL, 32);
    enc_size += __int64_t_encoded_array_size(NULL, 1);
    enc_size += __int32_t_encoded_array_size(NULL, 1);
    for (int a0 = 0; a0 < this->participants; a0++) {
        enc_size += this->certificates_participants[a0]._getEncodedSizeNoHash();
    }
    enc_size += __int32_t_encoded_array_size(NULL, 1);
    for (int a0 = 0; a0 < this->joining; a0++) {
        enc_size += this->certificates_joining[a0]._getEncodedSizeNoHash();
    }
    enc_size += this->self._getEncodedSizeNoHash();
    enc_size += __int32_t_encoded_array_size(NULL, 1);
    enc_size += __int32_t_encoded_array_size(NULL, 1);
    enc_size += __byte_encoded_array_size(NULL, this->sig_size);
    return enc_size;
}

uint64_t Dutta_Barua_JOIN_response::_computeHash(const __lcm_hash_ptr *p)
{
    const __lcm_hash_ptr *fp;
    for(fp = p; fp != NULL; fp = fp->parent)
        if(fp->v == Dutta_Barua_JOIN_response::getHash)
            return 0;
    const __lcm_hash_ptr cp = { p, Dutta_Barua_JOIN_response::getHash };

    uint64_t hash = 0x4d3e4a044678044dLL +
         Dutta_Barua_cert::_computeHash(&cp) +
         Dutta_Barua_cert::_computeHash(&cp) +
         Dutta_Barua_cert::_computeHash(&cp);

    return (hash<<1) + ((hash>>63)&1);
}

#endif
